# Generated by Django 3.1.2 on 2021-03-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursor',
            new_name='Curso',
        ),
    ]
